### ISSUE TITLE
Limpiar Canvas cada vez que se dibuja

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2019-favaro-menel#4]
![imagen](https://user-images.githubusercontent.com/8345007/59979568-fc8e7f00-95bf-11e9-8e75-48c81fa92475.png)

**Comment by AngeloMenel98** [comment]
Como lo podemos hacer?

**Comment by edme88** [comment]
https://stackoverflow.com/questions/2142535/how-to-clear-the-canvas-for-redrawing

```
const context = canvas.getContext('2d');

context.clearRect(0, 0, canvas.width, canvas.height);
````
